const instalistMockData = [
  {
    nodeId: "5f2c18a68ac42c7d7c3efee4",
    nodeType: "1",
    displayName: "Fresh Fruits",
    description: null,
    tags: ["INSTAMART_L2_CAROUSEL_BANNER__FRESH FRUITS"],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId:
      "NI_CATALOG/IMAGES/CIW/2024/4/10/7e69ee83-c2cf-4ec4-8846-f29cfbc245e1_b93013a9-c9c1-4dd8-b146-97e4c98b3a81",
    productCount: 81,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "652548c2b1e95a00013af5d5",
    nodeType: "1",
    displayName: "Mangoes & Melons",
    description: null,
    tags: [],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId:
      "NI_CATALOG/IMAGES/CIW/2024/3/7/25a96244-98ce-4db4-b9db-71e7126f4e0a_83fa0980-1979-4381-8712-48f91efb3e0e",
    productCount: 25,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "65150f71ad4645000136d090",
    nodeType: "1",
    displayName: "Exotic Fruits",
    description: null,
    tags: [],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId: "0deb120fa1781361c746c8e4e3da30e1",
    productCount: 14,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "61360b168ac42c7f24025bcb",
    nodeType: "1",
    displayName: "Festive Essentials",
    description: null,
    tags: ["INSTAMART_L2_CAROUSEL_BANNER__FLOWERS"],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId: "hledvzf17rtauuhh3atg",
    productCount: 22,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "6583ff1fa944420001391f44",
    nodeType: "1",
    displayName: "Flowers & Plants",
    description: null,
    tags: [],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId: "b4927e51ec8807a4570a34b34acd80ba",
    productCount: 10,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "6461c05882b1120a888bd5a1",
    nodeType: "1",
    displayName: "Newly Launched",
    description: null,
    tags: [],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId:
      "NI_CATALOG/IMAGES/CIW/2024/3/8/9d0784d1-8efe-48b3-980b-8c488227b5de_eda5280c-890b-4663-9a63-e92e1138e84f",
    productCount: 83,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "5f2c18a68ac42c7d7c3efee6",
    nodeType: "1",
    displayName: "Fresh Cuts and Juices",
    description: null,
    tags: ["INSTAMART_L2_CAROUSEL_BANNER__RECIPE MIXES AND CUTS"],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId: "bd0aef6befee1575f129aaef4a16d76e",
    productCount: 45,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "5f2c18a68ac42c7d7c3efee5",
    nodeType: "1",
    displayName: "Fresh Vegetables",
    description: null,
    tags: ["INSTAMART_L2_CAROUSEL_BANNER__FRESH VEGETABLES"],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId: "3e346856b1ae40d2c87ef71a515ee80a",
    productCount: 147,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "5f2c18a68ac42c7d7c3efee9",
    nodeType: "1",
    displayName: "Leafy and Seasonings",
    description: null,
    tags: ["INSTAMART_L2_CAROUSEL_BANNER__LEAFY AND SEASONINGS"],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId: "lyoroz8bib2nzayrbxwu",
    productCount: 46,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "60d2cbaa8ac42c7f24024829",
    nodeType: "1",
    displayName: "Certified Organics",
    description: null,
    tags: [
      "INSTAMART_L2_CAROUSEL_BANNER_FNVORGANIC",
      "INSTAMART_L2_CAROUSEL_BANNER__CERTIFIED ORGANICS",
    ],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId: "fen6wkhlijaxd2hzkckk",
    productCount: 40,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "65150f921a29ce00013bac59",
    nodeType: "1",
    displayName: "Exotic Vegetables",
    description: null,
    tags: [],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId: "nshfziwjldwihnnmizxi",
    productCount: 30,
    textColor: null,
    analytics: null,
  },
  {
    nodeId: "63be96a06dfe1809ebf68d9a",
    nodeType: "1",
    displayName: "Regional Favorites",
    description: null,
    tags: ["INSTAMART_L2_CAROUSEL_BANNER_FnV_REGIONAL FAVORITES"],
    enableUnstructuredOrderFlow: false,
    ageConsentRequired: false,
    nodes: null,
    imageId: "43278ed0c64ccfeb661823466284da6f",
    productCount: 22,
    textColor: null,
    analytics: null,
  },
];

export default instalistMockData;
